version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: city_library_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: city_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web

  city-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: city_library_service
    restart: unless-stopped
    environment:
      - "SPRING_PROFILES_ACTIVE=prod" #dev
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - web

networks:
  web:
    driver: "bridge"
    name: web

volumes:
  db-volume: { }
