version: '3.7'

services:
  db:
    build: .
    container_name: city_library_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: city_library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web

networks:
  web:
    driver: "bridge"

volumes:
  db-volume: { }
