version: '3.7'

services:
  city-database:
    container_name: city_database
    image: city_database:latest
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - web

  city-service:
    container_name: city_service
    image: city_service:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE
      - SPRING_MAIL_USERNAME
      - SPRING_MAIL_PASSWORD
      - POSTGRES_DB_URL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - JWT_GENERATOR_SIGNATURE_SECRET
      - FRONTEND_HOST
      - EMAIL_VERIFICATION_ENDPOINT
      - PASSWORD_RESET_CONFIRMATION_ENDPOINT
      - JAVA_OPTS
    ports:
      - '8080:8080'
    depends_on:
      - city-database
    networks:
      - web

networks:
  web:
    driver: "bridge"
    name: web

volumes:
  db-volume: { }
