server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: city-libra
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://city_library_db:5432/city_library
    username: postgres
    password: secret
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false    #true|false
    hibernate:
      ddl-auto: none  #update  create

  jackson:
    default-property-inclusion: always

  flyway:
    enabled: true
    validate-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8180/auth/realms/city-library/protocol/openid-connect/certs'

springdoc:
  swagger-ui:
    enabled: true #true|false

app:
  keycloak:
    auth-url: 'http://localhost:8180/auth/realms/city-library/protocol/openid-connect'
    client-id: 'city-library-client'
