spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/city_library
    username: postgres
    password: secret
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true    #true|false
    hibernate:
      ddl-auto: none  #update  create

logging:
  level:
    ROOT: info
    com.example: debug
#    org.springframework.cache: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.SQL: debug
#    org.springframework.web.client.RestTemplate: trace
