server:
  port: 8080

spring:
  application:
    name: city-library-service

  jackson:
    default-property-inclusion: always

  flyway:
    enabled: true
    validate-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    defaultEncoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  swagger-ui:
    enabled: true #true|false

jwt:
  token:
    secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    expired: 3600000

frontend:
  server:
    host: { FRONTEND_HOST }

endpoint:
  email-verification: { FRONTEND_EMAIL_VERIFICATION_PAGE }
