spring:
  datasource:
    url: jdbc:postgresql://city_library_db:5432/city_library
    username: postgres
    password: secret
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none


