server:
  port: 8080

spring:
  application:
    name: city-librar

  datasource:
    url: jdbc:postgresql://localhost:5432/city_library
    username: postgres
    password: secret
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false    #true|false
    hibernate:
      ddl-auto: none  #update  create

  jackson:
    default-property-inclusion: always

  flyway:
    enabled: true
    validate-on-migrate: true

#logging:
#  level:
#    ROOT: info
#    com.example: debug
#    org.springframework.cache: trace
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.SQL: debug
#    org.springframework.web.client.RestTemplate: trace

springdoc:
  swagger-ui:
    enabled: true #true|false

jwt:
  token:
    secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    expired: 3600000